location ^~ /ios/2c9715755397490791ffbe1568d2b914/ {
    alias /var/www/ke-ota/;
    index index.html;
    autoindex off;

    types {
        text/html html;
        text/xml plist;
        application/octet-stream ipa;
    }

    add_header Cache-Control "private, no-store" always;
    add_header X-Content-Type-Options "nosniff" always;
}
